### PR TITLE
added bower package file

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by srigi** [comment]
+1
there is no throttle/debounce lib in `bower` at this time.

**Comment by mreinstein** [comment]
@srigi  underscore has this functionality too: https://github.com/documentcloud/underscore

**Comment by andruby** [comment]
+1 @cowboy, are you planning to add this? 
The file should be renamed to bower.json though (which is the new convention as of bower 0.9.0)

**Comment by heruan** [comment]
+1

**Comment by antoniofrignani** [comment]
+1, Is this going to be merged?

**Comment by emagnier** [comment]
+1
@cowboy: I hope you will merge it soon :+1:

**Comment by wheresrhys** [comment]
+1 @cowboy  - merging this is a no-brainer, surely

**Comment by tomsommer** [comment]
+1 - See also #14

**Comment by tgdev** [comment]
+1

@cowboy - hopefully you merge this soon. Managing js plugins via bower is great!

**Comment by pixelbacon** [comment]
Really? Not merged yet?

**Comment by mreinstein** [comment]
jquery is antiquated. It's time to wean yourself off of it  http://substack.net/weaning_yourself_off_jquery

**Comment by tomsommer** [comment]
That's ridiculous. bower.js has nothing to do with jQuery. 
This plugin still depends on jQuery, so either recode the plugin it or add bower.js with a jQuery dependance.

Either way, a bower.js file makes sense.

**Comment by mreinstein** [comment]
>  That's ridiculous. bower.js has nothing to do with jQuery. 

Whether or not it interoperates with bower is irrelevant. jquery and its' plugins are part of an antiquated development model, which the web cannot rid itself of fast enough IMO. 

Do _not_ rely on "helper" libraries or massive frameworks that bundle in everything + the kitchen sink. use individual modules that do one thing, with a clearly defined interface.

**Comment by tomsommer** [comment]
Your opinion, which makes me wonder why you have anything to do with this plugin.

**Comment by mreinstein** [comment]
> Your opinion

Indeed. Fortunately github is not a fascist regime, enabling us to form and share diverse opinions. :) You are certainly free to replicate my pull, and re-submit it if your heart passionately burns for this functionality. 

jquery was a wonderful invention, ushering in a new era of web development. It brought us away from user agent sniffing to testing actual feature support. It also gave a sane abstraction to do DOM traversal. However, given the improvements to `querySelectorAll`, `classList`, and other common bits, its' utility is diminishing. The next era of web development is going to be moving away from pulling in 2MB of pre-bundled utility functions and getting more granular/modular, pulling in just the stuff a given project needs.

> which makes me wonder why you have anything to do with this plugin.

Because times and the technology landscape change. rapidly. When I submitted this PR two years ago, it was already an old concept and jquery was starting to show it's age. 

Anyway, this is too much discussion for a closed PR on an outdated project.

**Comment by pixelbacon** [comment]
@mreinstein There are plenty of times to use legacy code bases. Any solid pice of code can have a jquery hook easy enough. And some projects have a requirement that the entry point needs to be pretty simple.

Is it ideal? No, but it is what it is. Are you really assuming nobody should ever have use for it?

More so, if you are in fact so dedicated to this dying... Then kill it. Delete the repo. And don't let anybody use "the kitchen sink" and move forward.

Otherwise let people use legacy when they need to. Come on now.

**Comment by mreinstein** [comment]
> There are plenty of times to use legacy code bases.

No one is remotely suggesting that legacy codebases should be ignored. Once again, you're free to submit your own PRs all day on this. It's not my project. I'm simply closing my own PR because a) the maintainer isn't interested or doesn't have time. and b) I'm not going to add a new feature to a legacy product that I wouldn't advocate using anyway.

> More so, if you are in fact so dedicated to this dying... Then kill it. Delete the repo. 

This isn't my project, and I'm not actively trying to "kill" anything. I'm just explaining my point for not adding a new contribution to someone else's legacy jquery plugin. Again, if this is so important, create your own PR. Maybe the maintainer will like yours more? 

> Otherwise let people use legacy when they need to. Come on now.

you could not have misrepresented the point more thoroughly.

**Comment by pixelbacon** [comment]
You missed me over exaggerating to you having such a strong opinion . I suggested deleting it because you had such gusto (I know you don't own the repo). You opened the ticket for a bower file. Many people see value in it. You skewered them as if they're misguided and have no business even needing it.  Closing it cuts off access and history at a glance, telling others to open a new one would just be repeating this situation; eventually someone would come in and say "NO" only in so many words.

Anyhow. Sorry the well intentioned sarcasm didn't communicate well.

**Comment by mreinstein** [comment]
> You skewered them as if they're misguided and have no business even needing it. 

Definitely not my intention to skewer, lambaste, roast, criticize, or critique what other people do with their software. As long as I don't have to maintain it later, do as you please. :P 

> Closing it cuts off access and history at a glance, telling others to open a new one would just be repeating this situation

meh, I don't think so. There's still a ticket for this https://github.com/cowboy/jquery-throttle-debounce/issues/13 so it's not like the history is gone.

> Sorry the well intentioned sarcasm didn't communicate well.

Yeah, someday someone will make a lot of money inventing a good way to express tone on the internet. :)

**Comment by pixelbacon** [comment]
:dart:

**Comment by selfthinker** [comment]
@mreinstein, the discussion about jQuery is irrelevant for this plugin as **it actually doesn't require jQuery**.
From http://benalman.com/projects/jquery-throttle-debounce-plugin/

> jQuery isn’t actually required for this plugin, because nothing internal uses any jQuery methods or properties. jQuery is just used as a namespace under which these methods can exist.

**Pull request closed without merging**
